from flask import Flask, render_template_string
import pandas as pd
import pickle
import numpy as np

# Load model and category mappings
with open("./models/model.pkl", "rb") as f:
    model = pickle.load(f)

with open("./models/cat_maps.pkl", "rb") as f:
    cat_maps = pickle.load(f)

# Path to the CSV file
# By default, the credit evaluation program webapp.py reads the input.csv file
# generated by the AI training program main.py.
# However, it can also read any CSV file as long as the format is identical.
CSV_FILE = "data/input.csv"

# Initialize Flask application
app = Flask(__name__)

# HTML template
HTML_PAGE = """
<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>Credit Scores - Table View</title>
  <style>
    table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
      padding: 5px;
      text-align: center;
    }
    .risk-high {
      background-color: #ffcccc;
      font-weight: bold;
    }
  </style>
</head>
<body>
  <h1>Credit Scores - Table View</h1>
  {{ table|safe }}
</body>
</html>
"""


@app.route("/", methods=["GET"])
def index():
    try:
        # Load CSV file
        df = pd.read_csv(CSV_FILE, encoding="utf-8-sig")

        # Create forward mapping (label → code) for each categorical column
        cat_maps_forward = {
            col: {label: code for code, label in mapping.items()}
            for col, mapping in cat_maps.items()
        }

        # Apply forward mapping to DataFrame
        # Convert only when the value matches a label; keep numeric codes unchanged
        for col, mapping_fwd in cat_maps_forward.items():
            if col in df.columns:
    
                def _to_code(x, mf=mapping_fwd):
                    return mf.get(x, x)

                df[col] = df[col].apply(_to_code)

        # Temporarily store the target column
        delinquency_info_col = None
        if "DelinquencyInfo" in df.columns:
            delinquency_info_col = df["DelinquencyInfo"].copy()
            df = df.drop(columns=["DelinquencyInfo"])

        # Extract features (total 19 columns)
        feature_cols = [
            "Sex",
            "Marital",
            "Age",
            "Income",
            "CreditAppAmount",
            "OtherDebts",
            "DebtRestruct",
            "BorrowingRatio",
            "JobType",
            "Occupation",
            "Industry",
            "Education",
            "Dependents",
            "OwnHouse",
            "Foreigner",
            "Phone",
            "EmploymentYears",
            "Guarantor",
            "Collateral",
        ]
        X = df[feature_cols].copy()

        # Scoring (calculate probability of delinquency)
        proba_list = model.predict_proba(X)[:, 1]
        df["Score"] = np.round(proba_list, 4)

        # Restore the target column if it exists
        if delinquency_info_col is not None:
            df["DelinquencyInfo"] = delinquency_info_col

        # Reverse mapping for display (code → label)
        # Converts numeric codes back to their corresponding labels for display purposes.
        # If a value does not match any code in the mapping, keep it unchanged.
        for col, mapping in cat_maps.items():  # cat_maps は {コード:ラベル}
            if col in df.columns:

                def _to_label(x, m=mapping):
                    return m.get(x, x)  # マッチしなければ元の値

                df[col] = df[col].apply(_to_label)
        # Columns to display (customizable)
        display_cols = [
            "Name",
            "Sex",
            "Age",
            "Income",
            "BorrowingRatio",
            "Industry",
            "CreditAppAmount",
            "OtherDebts",
            "DelinquencyInfo",
            "DebtRestruct",
            "Score",
        ]

        # Highlight scores >= 0.7 in red
        def highlight_risk(val):
            try:
                return 'class="risk-high"' if float(val) >= 0.7 else ""
            except:
                return ""

        # Convert table to HTML format
        table_html = df[display_cols].to_html(
            index=False,
            escape=False,
            border=1,
            formatters={"Score": lambda x: f"<span {highlight_risk(x)}>{x}</span>"},
        )

        return render_template_string(HTML_PAGE, table=table_html)

    except Exception as e:
        return render_template_string(
            HTML_PAGE, table=f"<p style='color:red;'>Error: {e}</p>"
        )


if __name__ == "__main__":
    # The Flask application's default port is set to 8080 for this project.
    # This value is not fixed — you can change it to any available port as needed.
    app.run(host="0.0.0.0", port=8080)
